### ISSUE TITLE
Jetpack Compose samples

### ISSUE THREAD

**Issue by mochadwi** [KStateMachine/kstatemachine#30] opened 2022-05-26 05:29 UTC

**Comment by nsk90** [comment] 2023-04-09 15:56
Sample Compose app should be created to show KStateMachine library possibilities. This app may be similar to https://github.com/nsk90/android-kstatemachine-sample but it is not mandatory.

The app should use simple MVI implementation like in Android sample and Kotlin Coroutines library. 
There should be no other third party dependencies.

The goal is to make a state machine library sample, so UI should be minimal clean and simple.

**Comment by chanjungkim** [comment] 2023-04-10 11:37
@nsk90 in where do you want to place the sample folder?

**Comment by nsk90** [comment] 2023-04-10 12:27
That should be separate repository, I will make it..

**Comment by nsk90** [comment] 2023-04-10 12:50
https://github.com/nsk90/compose-kstatemachine-sample
This is an empty repository to start from

**Comment by davehorner** [comment] 2024-08-24 04:11
I'm looking at this tonight based on the https://github.com/kstatemachine/android-kstatemachine-sample which uses "0.26.0" which builds and seems to run to a point.

if I move to 0.30.0
<img width="524" alt="image" src="https://github.com/user-attachments/assets/ebd9c047-150c-4df6-a10f-384c970e9836">
the shooting 
```
            val shooting = addState(Shooting())
```
also does not resolve.
Both of these are the HeroStates() with member variables; and I have looked some and don't see the same associated state being done in other examples.  I will keep playing and thanks for your code.  I saw some notes about version migration but did not find guidance on transitioning from 0.26.0.

**Comment by davehorner** [comment] 2024-08-24 11:52
kmp compose;   https://github.com/KStateMachine/kstatemachine/compare/master...davehorner:kstatemachine:master
I don't have it figured yet and I see that it can crash when the machine is setup improperly (I assume its me; the existing sample at 0.26.0 works fine)  Koin, voyager, ImageCoil, compose

**Comment by davehorner** [comment] 2024-08-25 10:05
I realize you said it should be a separate repository; if you dont want it in tree I can move it out.  

It moves through all the states when it starts for some reason.
2024-08-25 06:00:08.644 22909-22909 <no-tag>                org.example.project                  I  State updated: ModelData(ammoLeft=40, activeStates=[Standing($143799930)])
2024-08-25 06:00:08.729 22909-22909 <no-tag>                org.example.project                  I  State Entered: AirAttacking($98229508)
2024-08-25 06:00:08.731 22909-22909 <no-tag>                org.example.project                  I  State Entered: NotShooting($351155)
2024-08-25 06:00:08.735 22909-22909 <no-tag>                org.example.project                  I  State Entered: Standing($143799930)

The statemachine will crash the process.
                                                                                                    Process: org.example.project, PID: 22909
                                                                                                    java.lang.IllegalStateException: Multiple transitions match com.stickman.ControlEvent$DuckPressEvent@c54fd37, [DefaultTransition(start transition)] in StateMachineImpl(Hero)

I have the same machine that is in the example.  I'm not sure how to fix it or how to protect against a crash when using this library.

**Comment by nsk90** [comment] 2024-08-28 12:44
there is a empty repo for this sample https://github.com/KStateMachine/compose-kstatemachine-sample

**Comment by davehorner** [comment] 2024-08-28 15:23
I can push it there; but its not even worth sharing in its current state.

**Comment by davehorner** [comment] 2024-08-28 15:28
https://github.com/davehorner/compose-kstatemachine-sample

**Comment by davehorner** [comment] 2024-08-31 18:05
aside from location, do you have any thoughts on what's wrong here?

**Comment by nsk90** [comment] 2024-09-02 06:32
Hi sorry for long replying, I was little bit busy.
I have moved Android Sample to KStateMachine v0.30.0. there were some breaking changes, I had to fix imports and an arguments order of a lambda function. 

You can see the difference here https://github.com/KStateMachine/android-kstatemachine-sample/commit/bbe8409e9709242745dddea1ec24340420994437#diff-9abb5da1e70e00c44d05a85f93fe11cbbe7927a0f2c4e247438c94a98a495199

**Comment by davehorner** [comment] 2024-09-02 17:06
If you have time to take a look at the sample. I would appreciate the feedback.  I am interested in using the library but have concerns with the way in which it crashes the application.

```
Process: org.example.project, PID: 19933
                                                                                                    java.lang.IllegalStateException: Multiple transitions match com.stickman.ControlEvent$JumpCompleteEvent@481486f, [DefaultTransition(start transition)] in StateMachineImpl(Hero)
                                                                                                    	at ru.nsk.kstatemachine.state.BaseStateImpl.recursiveFindUniqueResolvedTransition$suspendImpl(BaseStateImpl.kt:177)
                                                                                                    	at ru.nsk.kstatemachine.state.BaseStateImpl.recursiveFindUniqueResolvedTransition$kstatemachine(Unknown Source:0)
                                                                                                    	at ru.nsk.kstatemachine.statemachine.StateMachineImpl.doProcessEvent(StateMachineImpl.kt:328)
```

The FSM might be configured incorrectly.  Is there a way to trap this error or protect against the machine causing the application to terminate?

**Comment by davehorner** [comment] 2024-09-03 02:01
found the doNotThrowOnMultipleTransitionsMatch CreationArguments Boolean.

createStateMachineBlocking(screenModelScope, "Hero", ChildMode.PARALLEL,creationArguments = StateMachine.CreationArguments(doNotThrowOnMultipleTransitionsMatch=true))

that stops the crashing.  The sample does not work yet.  The activeStates is always Standing.

**Comment by nsk90** [comment] 2024-09-03 13:11
1) the the source of the problem is line 82 `val airAttacking = addState(AirAttacking())`. It should be inside `state("Movement")` block.
2) I fixed the exception message (there was a mistake), and published new library version 0.31.0 with it.

**Comment by davehorner** [comment] 2024-09-03 19:08
committed those changes; thank you much

it gets stuck in ducking...not quite there.

**Comment by davehorner** [comment] 2024-09-04 02:07
Ok, I just hadn't setup the press and release.  I've submitted a PR.

**Comment by nsk90** [comment] 2024-09-06 07:08
https://github.com/KStateMachine/compose-kstatemachine-sample

**Comment by nsk90** [comment] 2024-09-06 07:09
Thanks to @davehorner !

**Closed by nsk90** 2024-09-06 07:08 UTC
Labels: enhancement, good first issue
